import type { Category } from "@/lib/types/domain";
import { stripAccents } from "@/lib/normalization/rules";

/**
 * Mots-cles (normalises produit, en minuscules, sans accents) -> categorie.
 * La premiere correspondance l'emporte ; ajouter une entree suffit a
 * ameliorer la couverture.
 */
export const CATEGORY_KEYWORDS: Array<{ category: Category; keywords: string[] }> = [
  {
    category: "Frais",
    keywords: [
      "lait",
      "yaourt",
      "yaourts",
      "yogourt",
      "fromage",
      "mozzarella",
      "beurre",
      "creme",
      "oeuf",
      "jambon",
      "charcuterie",
      "saucisse",
      "chorizo",
      "viande",
      "poisson",
      "saumon",
      "poulet",
      "boeuf",
      "porc",
      "veau",
      "agneau",
      "tofu",
    ],
  },
  {
    category: "Fruits & Legumes",
    keywords: [
      "banane",
      "pomme",
      "tomate",
      "salade",
      "carotte",
      "oignon",
      "citron",
      "fruit",
      "legume",
      "avocat",
      "poire",
      "orange",
      "peche",
      "abricot",
      "fraise",
      "framboise",
      "raisin",
      "kiwi",
      "ananas",
      "melon",
      "pasteque",
      "endive",
      "poireau",
      "courgette",
      "aubergine",
      "champignon",
      "brocoli",
      "epinard",
      "radis",
      "concombre",
      "poivron",
      "chou",
      "primeur",
    ],
  },
  {
    category: "Surgeles",
    keywords: ["surgele", "glace", "frites surgelees", "poisson pane"],
  },
  {
    category: "Epicerie",
    keywords: [
      "pates",
      "riz",
      "raviolis",
      "cereales",
      "biscuits",
      "chocolat",
      "confiture",
      "huile",
      "farine",
      "sucre",
      "sel",
      "conserve",
      "soupe",
      "cafe",
      "the",
      "pain",
      "miche",
      "baguette",
      "brioche",
      "tartine",
      "crepe",
      "crepes",
      "biscotte",
      "moutarde",
      "mayonnaise",
      "ketchup",
      "lentille",
      "semoule",
      "couscous",
      "farfalle",
      "coquillette",
    ],
  },
  {
    category: "Boissons",
    keywords: ["eau", "jus", "soda", "biere", "vin", "boisson"],
  },
  {
    category: "Hygiene",
    keywords: [
      "deodorant",
      "dentifrice",
      "shampoing",
      "gel douche",
      "savon",
      "rasoir",
      "coton",
      "mouchoir",
      "papier toilette",
      "serviette hygienique",
    ],
  },
  {
    category: "Entretien",
    keywords: [
      "lessive",
      "liquide vaisselle",
      "eponge",
      "nettoyant",
      "javel",
      "lingette",
      "sac poubelle",
    ],
  },
  {
    category: "Bebe",
    keywords: ["couche", "lingette bebe", "lait infantile", "petit pot", "biberon"],
  },
  {
    category: "Animaux",
    keywords: ["croquette", "pate chat", "pate chien", "litiere"],
  },
  {
    category: "Bricolage",
    keywords: ["ampoule", "pile", "outil", "visserie", "peinture"],
  },
];

export function normalizeForMatching(input: string): string {
  return stripAccents(input.toLowerCase()).trim();
}
